theme: jekyll-theme-slate
title: PL-200 - Training - Microsoft Power Platform Functional Consultant
description: Companion material and resources for the course 'Microsoft Power Platform Functional Consultant' delivery by Ricardo Cabral. 
relative_links:
  enabled: true
  collections: true
exclude:
  - .github/
include:
  - README.md
author: Ricardo Cabral
twitter_username: rramoscabral
github_username:  rramoscabral
